"use client";

import { useState } from "react";
import { FileText, Download } from "lucide-react";

export type POData = {
  id: string;
  supplier: string;
  item: string;
  quantity: number;
  unitPrice: number;
  total: number;
};

export default function POCard({ data }: { data: POData }) {
  const [approved, setApproved] = useState(false);

  // Fungsi Sihir Cetak PDF Instan bawaan Browser
  const triggerPDFDownload = () => {
    window.print();
  };

  return (
    <div
      className={`my-4 p-5 border-2 rounded-xl bg-slate-50 transition-all ${approved ? "border-emerald-500" : "border-slate-300"}`}
    >
      <div className="flex justify-between items-start border-b border-slate-200 pb-3 mb-3">
        <div>
          <h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" /> Purchase Order Draft
          </h3>
          <p className="text-sm text-slate-600">Generated by SupplyMind AI</p>
        </div>
        <span className="bg-amber-100 text-amber-800 text-xs font-medium px-3 py-1 rounded-full">
          ID: {data.id}
        </span>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4 text-xs sm:text-sm mb-4">
        {" "}
        <div>
          <p className="font-semibold text-slate-700">Supplier</p>
          <p className="text-slate-900">{data.supplier}</p>
        </div>
        <div>
          <p className="font-semibold text-slate-700">Item Description</p>
          <p className="text-slate-900">{data.item}</p>
        </div>
        <div>
          <p className="font-semibold text-slate-700">Quantity</p>
          <p className="text-slate-900">{data.quantity.toLocaleString()}</p>
        </div>
        <div>
          <p className="font-semibold text-slate-700">Total Estimated Cost</p>
          <p className="text-xl font-bold text-slate-950">
            Rp {data.total.toLocaleString("id-ID")}
          </p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-2 mt-2">
        {" "}
        {approved ? (
          <div className="flex-1 bg-emerald-100 text-emerald-800 text-center p-3 rounded-lg font-semibold">
            Approved & Sent to ERP
          </div>
        ) : (
          <button
            onClick={() => setApproved(true)}
            className="flex-1 bg-slate-900 text-white p-3 rounded-lg font-semibold hover:bg-slate-700 transition"
          >
            Approve & Send
          </button>
        )}
        {/* Tombol Cetak PDF Show-stopper */}
        <button
          onClick={triggerPDFDownload}
          className="p-3 bg-white border border-slate-300 rounded-lg text-slate-700 hover:bg-slate-50 transition flex items-center justify-center"
          title="Download as PDF"
        >
          <Download className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
}
